/**
 * Material system color tokens.
 *
 * Upstream1: {@link https://github.com/material-components/material-web/tree/main/tokens}
 *
 * Upstream2 (self-hosted deployment, not the official m3.material.io): {@link https://material-theme-builder.sandlada.com/}
 *
 * Previously served via contributes.css.customData; that namespace is now
 * claimed by a proposed-API CSS extension point, so tokens ship as css
 * language snippets instead (snippets/css.code-snippets).
 */
export const cssTokens: string[] = [
    '--md-sys-color-primary-key-color',
    '--md-sys-color-secondary-key-color',
    '--md-sys-color-tertiary-key-color',
    '--md-sys-color-error-key-color',
    '--md-sys-color-neutral-key-color',
    '--md-sys-color-neutral-variant-key-color',
    '--md-sys-color-background',
    '--md-sys-color-error',
    '--md-sys-color-error-container',
    '--md-sys-color-error-dim',
    '--md-sys-color-inverse-on-surface',
    '--md-sys-color-inverse-primary',
    '--md-sys-color-inverse-surface',
    '--md-sys-color-on-background',
    '--md-sys-color-on-error',
    '--md-sys-color-on-error-container',
    '--md-sys-color-on-primary',
    '--md-sys-color-on-primary-container',
    '--md-sys-color-on-primary-fixed',
    '--md-sys-color-on-primary-fixed-variant',
    '--md-sys-color-on-secondary',
    '--md-sys-color-on-secondary-container',
    '--md-sys-color-on-secondary-fixed',
    '--md-sys-color-on-secondary-fixed-variant',
    '--md-sys-color-on-surface',
    '--md-sys-color-on-surface-variant',
    '--md-sys-color-on-tertiary',
    '--md-sys-color-on-tertiary-container',
    '--md-sys-color-on-tertiary-fixed',
    '--md-sys-color-on-tertiary-fixed-variant',
    '--md-sys-color-outline',
    '--md-sys-color-outline-variant',
    '--md-sys-color-primary',
    '--md-sys-color-primary-container',
    '--md-sys-color-primary-dim',
    '--md-sys-color-primary-fixed',
    '--md-sys-color-primary-fixed-dim',
    '--md-sys-color-scrim',
    '--md-sys-color-secondary',
    '--md-sys-color-secondary-container',
    '--md-sys-color-secondary-dim',
    '--md-sys-color-secondary-fixed',
    '--md-sys-color-secondary-fixed-dim',
    '--md-sys-color-shadow',
    '--md-sys-color-surface',
    '--md-sys-color-surface-bright',
    '--md-sys-color-surface-container',
    '--md-sys-color-surface-container-high',
    '--md-sys-color-surface-container-highest',
    '--md-sys-color-surface-container-low',
    '--md-sys-color-surface-container-lowest',
    '--md-sys-color-surface-dim',
    '--md-sys-color-surface-tint',
    '--md-sys-color-surface-variant',
    '--md-sys-color-tertiary',
    '--md-sys-color-tertiary-container',
    '--md-sys-color-tertiary-dim',
    '--md-sys-color-tertiary-fixed',
    '--md-sys-color-tertiary-fixed-dim',
]
